# Generated by Django 5.0 on 2023-12-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fraud_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraud_report',
            name='box_check',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
